### ISSUE TITLE
Proposal: add searches for packages in search-box

### ISSUE THREAD

**Issue by k-bx** [fpco/stackage-server#101]
Proposal is to add a feature to be able to search for a specific package in top-right search-box on stackage website.

**Comment by DanBurton** [comment]
Related: sometimes I've wanted to limit the scope of a hoogle search to a given package. I think hayoo might be able to do this.

**Comment by chrisdone** [comment]
Hoogle can do that, but I don't recall the syntax.

**Comment by mgsloan** [comment]
Yeah, hoogle's syntax for that is `+lens`. It looks like our stackage server integration of Hoogle doesn't do that, but queries restricted by module, such as `+Control.Lens` do work.  I've split off an issue about this.

**Comment by mgsloan** [comment]
Also, I don't feel the need for searching for a specific package, due to the following two approaches working:

* Visit a snapshot, like http://www.stackage.org/lts, and use browser search (ctrl+f) to find the package

* If I'm looking for a specific package by name, to see what snapshots contain it, I just construct a url by appending the package name to `http://www.stackage.org/package/`, like http://www.stackage.org/package/lens

**Comment by snoyberg** [comment]
@k-bx I am a bit concerned that two search boxes on a page will end up confusing people. What if we had a link like "find a page" that took you to the list of all packages? Would that address your concern here?

**Comment by k-bx** [comment]
@snoyberg yeah, by no means I was proposing two search-boxes. Ideally, I would see it as somehow injecting search-results with a small "packages match" box, that would combine, for a search of "lens" packages: lens (exact match), lens*, *lens*. Limited by 10, for example.

Having a link to being able to "browse" packages (let's begin with having a full list of current lts) is also more than suitable.

I usually also just edit URL to go to package, but I didn't have "first" url to start with, so didn't know it's the same as in Hackage, so now I also found URL somehow and am editing it, there's no more problem for me.

**Comment by DanBurton** [comment]
The list of LTS packages can be found at https://www.stackage.org/lts

**Comment by snoyberg** [comment]
@chrisdone Design wise, what do you think about adding a "browse LTS packages" link underneath the Hoogle search box on the homepage?

**Comment by chrisdone** [comment]
Seems fine. Same link as what Dan wrote? http://www.stackage.org/lts

**Comment by snoyberg** [comment]
Yes

**Comment by k-bx** [comment]
Proposal from me: https://i.imgur.com/0h9vWiP.png

**Comment by snoyberg** [comment]
Looks good. Would you be interested in sending a pull request against the
stackage-content repo.

**Comment by k-bx** [comment]
Will do

**Comment by snoyberg** [comment]
Cool thanks!

**Comment by k-bx** [comment]
Perfect :) Thanks.
