### ISSUE TITLE
Not all libraries have link to "Source"

### ISSUE THREAD

**Issue by sfilipov** [fpco/stackage-server#111]
I found out that parts of the documentation for some libraries does not provide a "Source" link on the right, next to the name of a method. For comparison, the documentation hosted at https://www.haskell.org/hoogle/ has this kind of link for the same library. I only found that problem with [Base 4.7.0.2](http://haddock.stackage.org/lts-2.19/base-4.7.0.2/) but I suspect that more libraries are affected. In addition, not all libraries are affected i.e. Prelude has "Source" links.

Here's an example of such link for Data.List at [Hoogle](https://www.haskell.org/hoogle/)
![screenshot from 2015-07-20 16 35 43](https://cloud.githubusercontent.com/assets/2607726/8777122/b396561e-2efe-11e5-9f32-b280a414945e.png)

Here's how it looks at [Stackage.org](http://www.stackage.org/)
![screenshot from 2015-07-20 16 41 47](https://cloud.githubusercontent.com/assets/2607726/8777129/c0b4b39a-2efe-11e5-9282-d7b48e202cfd.png)

I am sorry if this is not the right place to raise the issue.

**Comment by snoyberg** [comment]
I pinged @hvr about this, the core libraries in the GHC PPA we use doesn't have the source links included. I don't know if there's an ETA on getting that fixed. We could consider moving directly to the haskell.org bindists instead, but I've been avoiding it until now.

**Comment by snoyberg** [comment]
This is now fixed for all new-ish snapshots (past two weeks or so), please report if you see something missing in new snapshots.
