### ISSUE TITLE
Atom feed for changes

### ISSUE THREAD

**Issue by mathstuf** [fpco/stackage-server#112]
It'd be great if an Atom (or RSS) feed were available for any changes. Something like:

```
.../lts/news.atom
.../nightly/news.atom
.../news.atom
```

**Comment by zudov** [comment]
It's now fully done:

- http://stackage.org/feed
- http://stackage.org/feed/lts
- http://stackage.org/feed/lts-3
- http://stackage.org/feed/nightly

**Comment by mathstuf** [comment]
Thanks!
