### ISSUE TITLE
Document valid resolver values for Stack

### ISSUE THREAD

**Issue by nkaretnikov** [fpco/stackage-server#113]
On stackage.org, there are cabal-install instructions, but nothing really explains how to use different Stackage sets with Stack (i.e., valid `resolver` values).

**Comment by snoyberg** [comment]
Sounds like a good change, and should be relatively isolated. Would you be
interested in sending a PR?

**Comment by nkaretnikov** [comment]
> Sounds like a good change, and should be relatively isolated. Would you be
> interested in sending a PR?

Maaaaybe sometime later, but probably not, sorry.  Too much on my plate
already.
