### ISSUE TITLE
Home page Hoogle search box doesn't work anymore (no LTS-3.3 hoogle db yet)

### ISSUE THREAD

**Issue by rvion** [fpco/stackage-server#117]
home page hoogle search box **doesn't return any result** as of now. 
eg: http://www.stackage.org/lts-3.3/hoogle?q=alloca
but does for previous lts: (lts-3.2, http://www.stackage.org/lts-3.2/hoogle?q=alloca)
I report this bug because it's been a few hours already, and I have the impression it's not because of hoogle db generation delay

**Comment by snoyberg** [comment]
Looks like a bug in stackage-curator, may take some time

**Comment by snoyberg** [comment]
I believe I've found the bug and fixed it. The easiest fix will be to just generate a new LTS release which will include the patched files. Hopefully all of this will deploy in the next 24 hours. Thanks for the report.

**Comment by snoyberg** [comment]
Newest nightly has Hoogle again, and I'm running an LTS build now. I'm going to close this as fixed, thanks for reporting.

**Comment by rvion** [comment]
thanks for the quick fix :)

**Comment by rvion** [comment]
just for the record, lts-3.4 works but lts-3.3 remains without documentation (https://www.stackage.org/lts-3.3/hoogle?q=map)
