### ISSUE TITLE
Produce hyperlinked sources

### ISSUE THREAD

**Issue by zudov** [fpco/stackage-server#125]
[Hyperlinked sources](https://hackage.haskell.org/package/base-4.8.1.0/docs/src/Prelude.html) are really nice. We should have them.

**Comment by snoyberg** [comment]
This is already done, and as new builds are processed are being populated. See, e.g., http://haddock.stackage.org/lts-3.8/yesod-1.4.2/src/Yesod.Default.Config.html

**Comment by zudov** [comment]
Great. It's even better, when it's already done :)

**Comment by jtojnar** [comment]
Is there any reason why this no longer works?

* [lts-3.20](http://haddock.stackage.org/lts-3.20/yesod-1.4.2/src/Yesod.Default.Config.html) is hyperlinked
* [lts-3.21](http://haddock.stackage.org/lts-3.21/yesod-1.4.2/src/Yesod-Default-Config.html) is not
* [lts-4](http://haddock.stackage.org/lts-4.2/yesod-1.4.2/src/Yesod-Default-Config.html) is not
* [lts-5](http://haddock.stackage.org/lts-5.17/yesod-1.4.3/src/Yesod-Default-Config.html) is not

**Comment by chrisdone** [comment]
@snoyberg any idea?

**Comment by snoyberg** [comment]
There were bugs in the prerelease version of Haddock with this support, so we rolled back to the Haddock that ships with GHC. I'm not aware of any officially released version with support for this. Is that information outdated?

**Comment by mgsloan** [comment]
Closing, has hyperlinked sources.
