### ISSUE TITLE
Link from Haddocks to package page

### ISSUE THREAD

**Issue by rimmington** [fpco/stackage-server#135]
One feature I use often on Hackage is the "Contents" link, which links to the package page. On haddock.stackage.org, these links point to the Haddock package summary. This isn't exactly unexpected, but it does mean there's no quick way to go from Hoogle -> Haddock -> package info.

(I've got no idea how haddock.stackage.org is set up, so I'm dropping this issue here. Sorry if it's the wrong repo.)

**Comment by zudov** [comment]
:+1: for this.

It shouldn't be too hard to just patch the static pages after they are generated, but perhaps there is a better way?

(I also don't know much about how these haddocks are handled, besides that they are static pages lying on S3)

**Comment by snoyberg** [comment]
I've pushed a commit to stackage-curator, we should be able to see the change in the next day or two.

**Comment by snoyberg** [comment]
This is now implemented. See, for instance, the contents link at the top of: http://haddock.stackage.org/nightly-2015-10-24/AC-Vector-2.3.2/Data-Vector-Transform-T3.html

**Comment by zudov** [comment]
@snoyberg If you go [here](http://haddock.stackage.org/nightly-2015-10-23/servant-client-0.4.4.5/Servant-Common-Req.html) and press "Contents" it takes you to https://www.stackage.org/nightly-2015-10-23/package/servant-client-0.4.4.5/Servant-Common-Req.html, which is "Not found". Can it be related to that change?

**Comment by snoyberg** [comment]
Yes, it only affects that one nightly.
