### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by tinkyholloway** [fpco/stackage-server#136]
![screen shot 2015-10-27 at 14 45 38](https://cloud.githubusercontent.com/assets/12114047/10761682/6876e482-7cba-11e5-9694-ef857464cb3a.png)

**Comment by DanBurton** [comment]
Is this fixed now?

<img width="981" alt="screen shot 2015-10-27 at 9 38 51 am" src="https://cloud.githubusercontent.com/assets/713692/10765120/91891240-7c8e-11e5-84af-1e4ddad485e4.png">

**Comment by snoyberg** [comment]
Pinging @dysinger

**Comment by tinkyholloway** [comment]
Works for me. Thanks.

**Comment by dysinger** [comment]
We may need to deploy with a ephemeral volume or ebs volume if there is a large write space expected by the app

**Comment by tinkyholloway** [comment]
How much space do you need?

**Comment by denisshevchenko** [comment]
It's up!

**Comment by tinkyholloway** [comment]
This works for me. Thanks.
