### ISSUE TITLE
Server is unstable

### ISSUE THREAD

**Issue by ndmitchell** [fpco/stackage-server#137]
Trying out http://www.stackage.org/package/shake/badge/nightly, if I refresh several times in the browser, about 2 out of 3 times I get internal server error:

    SQLite3 returned ErrorIO while attempting to perform prepare "PRAGMA journal_mode=WAL;": disk I/O error

It's not all the time, and has worked a few times.

**Comment by snoyberg** [comment]
This is not related to badges, our new hosting is not as stable as I'd have
hoped for, talking to the sysadmins.

**Comment by ndmitchell** [comment]
Feel free to close this then, although it would be good if there was somewhere I could subscribe to for notifications of when it's stable once more, so I can start rolling out the badges.

**Comment by zudov** [comment]
Since badges is the content that is supposed to be included on external websites, we probably don't want to fail so miserably (even if it's not our fault, and it happens rarely).

Perhaps we could catch such exceptions and return a badge which would be saying "Stackage is down, no badge for you at the moment"

TODO: Think of a better way to put that information in a nice badge.

**Comment by snoyberg** [comment]
Have you seen any instability since my comment yesterday?

**Comment by ndmitchell** [comment]
Nope, but I haven't been monitoring extensively. Are you using uptimerobot.com yet? I still can't recommend them enough :)

**Comment by snoyberg** [comment]
Yes, I'm using then, and it hasn't triggered once actually

**Comment by ndmitchell** [comment]
Hmm, do you pass back the 500 code properly? And do you have it set up to demand a particular code? Given the instability I was seeing yesterday, it seems implausible it didn't fail.

**Comment by snoyberg** [comment]
Yes, it should use error codes. Could have been a load balance stickiness
issue between the multiple hosts.

**Comment by ndmitchell** [comment]
Seems stable now, so closing.

**Comment by ndmitchell** [comment]
Just hit this again from Hoogle, when trying to fetch https://www.stackage.org/lts/cabal.config:

    Internal Server Error
    SQLite3 returned ErrorIO while attempting to perform prepare "PRAGMA journal_mode=WAL;": disk I/O error

**Comment by denisshevchenko** [comment]
Still the same problem, `disk I/O error`...

**Comment by Tritlo** [comment]
I'm having the same problem.

**Comment by rvion** [comment]
me too

**Comment by snoyberg** [comment]
Already tracked by #136

**Comment by denisshevchenko** [comment]
It's up!
