### ISSUE TITLE
Out of step hoogle

### ISSUE THREAD

**Issue by fatlazycat** [fpco/stackage-server#142]
From LTS 3.15 you get hoogle 4.2.43 the download database from https://www.stackage.org/lts-3.15/db.hoo is in format 4.2.42.0

When attempting to start a local google server I get

Error: Wrong hoogle database version: found 4.2.42.0, expected 4.2.43.0

Thanks

**Comment by DanBurton** [comment]
Interesting observation. It's true, the version of hoogle we use to build a given LTS's hoogle database doesn't necessarily match the version of hoogle that "ships" with that LTS.

@snoyberg what do you think make sense, to automate the process of using the latest hoogle available, or just continue to manually upgrade the version of hoogle that we use?

**Comment by mgsloan** [comment]
It'd be really excellent if hoogle versioned the database format (instead of basing the version on the package version).

**Comment by snoyberg** [comment]
There's nothing we can reasonably change here. We need to build databases compatible with the version of Hoogle used by the server, not the LTS snapshot.

**Comment by fatlazycat** [comment]
Thanks for the info, i'll close
