### ISSUE TITLE
lts-3 appearing in place of lts-4 on package/ pages

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-server#144]
Very recently stackage now supports building for more than one major version of LTS.
lts-4.0 was built on Wed and then yesterday lts-3.21 was built.

This caused stackage-server to now refer to lts-3.21 instead of lts-4.0 on package/ pages in stackage.org: eg https://www.stackage.org/package/stack

I guess stackage-server should always point to the latest major LTS release.

**Comment by snoyberg** [comment]
Not yet deployed, will hopefully do later today.
