### ISSUE TITLE
Website shows `stack` version 9.9.9 although most recent is 1.0.0

### ISSUE THREAD

**Issue by sjakobi** [fpco/stackage-server#145]
http://www.stackage.org/package/stack

The headline should be "stack 1.0.0" instead of "stack 9.9.9".
Hackage shows v9.9.9 to be deprecated: http://hackage.haskell.org/package/stack-9.9.9

**Comment by snoyberg** [comment]
This is actually caused by [all-cabal-metadata](https://github.com/commercialhaskell/all-cabal-metadata/blob/master/packages/st/stack.yaml), and specifically [all-cabal-metadata-tool](https://github.com/commercialhaskell/all-cabal-metadata-tool) not taking deprecated packages into account.

**Comment by snoyberg** [comment]
I believe the commit I just pushed will resolve this, though it will take up to an hour for all the pieces to get rebuilt correctly so we can test.

**Comment by sjakobi** [comment]
Works! Thanks for the quick fix!
