### ISSUE TITLE
Would you be interested in supporting arm64?

### ISSUE THREAD

**Issue by gitfoxi** [fpco/stackage-server#154]
I have a 12-core build server. I'll try building all of stackage over the next few days. Would you be interested in hosting my build products on stackage.org assuming things go smoothly?

**Comment by rvion** [comment]
that would be awesome !

**Comment by snoyberg** [comment]
What build products would we be hosting?

**Comment by gitfoxi** [comment]
Whatever you like.

GHC, cabal and stack are built. Currently trying to build all of lts-5.1
but having some issues

**Comment by snoyberg** [comment]
This would make more sense to offer on the Stack issue tracker (where I'm sure it will be welcome). Specifically, hosting pre-built GHCs and Stack binaries would make a lot of sense. (We don't currently host any cabal-install binaries or pre-built library binaries.)

**Comment by gitfoxi** [comment]
Thanks. I'll post to the Stack issue tracker.

**Comment by chrisdone** [comment]
Thanks!
