### ISSUE TITLE
stack install quits without explanation

### ISSUE THREAD

**Issue by gitfoxi** [fpco/stackage-server#155]
stack install

Installs some packages from build-depends then quietly and without explanation stops doing that. Is there a log or something I can check?

Long story is that I copied the contents of lts-5.1 into my build-depends. I don't know much about stack, but after deleting lines with the word "install", stack started building and installing things in alphabetical order. Great.

Later, I returned hoping to see progress but, after installing most packages starting with `a`, stack decided to call it a day and head the pub. Seeing no messages or logs, I tried it again

    stack install

This time she finished building everything starting with `a` and a few things starting with `b` (up to `base-unicode-symbols-0.2.2.4`) before nodding off in a drunken stupor.

Stack is running on Ubuntu 14.04, ghc-10.7.3, aarch64 on a 12-core, 25GB armcloud instance with only 30GB disk. I checked that she hadn't run out disk, and she hadn't. But the other thing is that it's day-1 for me on this hardware platform -- just built ghc yesterday; cabal and stack this morning -- so probably not everything has been tested that well.

**Comment by snoyberg** [comment]
This would make more sense on the Stack mailing list or issue tracker, I don't see a connection between this report and Stackage Server.

**Comment by gitfoxi** [comment]
Thanks. I will post to the Stack issue tracker and I'll check out the stack mailing list.
