### ISSUE TITLE
add package names to hoogle search ?

### ISSUE THREAD

**Issue by simonmichael** [fpco/stackage-server#158]
Thanks for the per-snapshot hoogles, which is a great feature.

They don't seem to match package names, as http://hoogle.haskell.org does. Could this be added ?

**Comment by snoyberg** [comment]
This seems to be a new feature in Hoogle 5, which is currently in alpha. When Hoogle 5 is officially released, we'll be able to move over to it and get this functionality.

**Comment by chrisdone** [comment]
This is added, hoogle5 is deployed.

https://www.stackage.org/lts-6.7/hoogle?q=map+%2Bvector

**Comment by simonmichael** [comment]
Thanks!
