### ISSUE TITLE
"expected minor version match with ghc-3.10.7"

### ISSUE THREAD

**Issue by mkoloberdin** [fpco/stackage-server#162]
On Arch Linux with stock ghc 7.10.3:

$ stack install ghc-mod
Run from outside a project, using implicit global project config
Using resolver: lts-5.8 from implicit global project's config file: /home/mike/.stack/global-project/stack.yaml
stack will almost certainly fail with GHC below version 7.8
Valiantly attempting to run anyway, but I know this is doomed
For more information, see: https://github.com/commercialhaskell/stack/issues/648

Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-3.10.7 (x86_64) (based on resolver setting in /home/mike/.stack/global-project/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/mike/.stack/programs/x86_64-linux/

$ stack --version
Version 1.0.4.2 x86_64

$ stack path
Run from outside a project, using implicit global project config
Using resolver: lts-5.8 from implicit global project's config file: /home/mike/.stack/global-project/stack.yaml
stack will almost certainly fail with GHC below version 7.8
Valiantly attempting to run anyway, but I know this is doomed
For more information, see: https://github.com/commercialhaskell/stack/issues/648

Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-3.10.7 (x86_64) (based on resolver setting in /home/mike/.stack/global-project/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/mike/.stack/programs/x86_64-linux/

**Comment by bergmark** [comment]
This should probably go in the commercialhaskell/stack repository, but either way, you mention both `3.10.7` and `7.10.3`, the former seems to be a typo somewhere.

**Comment by mkoloberdin** [comment]
This has nothing to do with the server. Seems to be a stack bug: https://github.com/commercialhaskell/stack/issues/1903

**Comment by mgsloan** [comment]
Note that it isn't a stack bug, but a bug in a dependency https://github.com/bos/vector-binary-instances/issues/6
