### ISSUE TITLE
Clearer version info on package page

### ISSUE THREAD

**Issue by mgsloan** [fpco/stackage-server#163]
Take for example https://www.stackage.org/package/path-io :

![2016-03-14-171343_649x326_scrot](https://cloud.githubusercontent.com/assets/22570/13764007/1fcb9dde-ea08-11e5-8971-a8f5d1dce740.png)

At the top of the page it says `path-io 1.1.0`, but the module documentation is for `0.2.0`, as that is the version in lts-5.8.  My preference would be that the packages page that does not specify a particular resolver give the most recent version available in some snapshot.  One way or another, the version number at the top of the page should match the documentation links.

Also, I find the version info below the header visually confusing.  I think it's because they're both links with just a single comma between them.  It'd be better to have part of the text be a link, and possibly list them vertically:

> [Version 0.2.0](google.com) in LTS Haskell 5.8 (GHC 7.10.3) 
> [Version 1.1.0](google.com) in Stackage Nightly 2016-03-14 (GHC 7.10.3)

**Comment by DanBurton** [comment]
I believe @juhp's changes addressed this, they just need to be deployed. See: https://github.com/fpco/stackage-server/pull/159

**Comment by mgsloan** [comment]
Ah, correct!
