### ISSUE TITLE
No hoogle db seems to be available

### ISSUE THREAD

**Issue by jolmg** [fpco/stackage-server#164]
https://www.stackage.org/lts-5.8/hoogle?q=widgetFileReload
https://www.stackage.org/lts-5.8/db.hoo

Both of these return "The given Hoogle database is not available."

I've tried searching with the following snapshots:
nightly-2016-03-15
nightly-2016-03-14
nightly-2016-03-13
lts-5.8
nightly-2016-03-12
lts-5.7

Search box autocomplete and browsing by package or module still seem to work.

**Comment by snoyberg** [comment]
Thanks for the report. We just updated library versions, and the new Hoogle
databases need to get generated on the server. Hopefully that will be done
within the hour.

**Comment by jolmg** [comment]
Ah, I see. Thanks for replying promptly. I'll be closing the issue then.

**Comment by snoyberg** [comment]
At least lts-5.8 seems to be working now.

**Comment by jolmg** [comment]
You're right. Thank you.
