### ISSUE TITLE
stackage badges pointing to lts-3 still

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-server#165]
SSIA eg https://github.com/ndmitchell/hlint/blob/master/README.md

**Comment by zudov** [comment]
I don't follow. Here is what I see in the hlint's README:

1. The bagde's image is showing the version of hlint (1.9.31) which is included in the latest LTS (lts-5.9). That's what https://www.stackage.org/package/hlint/badge/lts is resolved to.
2. Clicking on the badge takes you to the package page on stackage, information on which is completely consistent with what the badge displays.

Is there something wrong with that, or am I not seeing something. I really can't find anything in those badges that would refer to `lts-3`.

**Comment by juhp** [comment]
[![Stackage version](https://www.stackage.org/package/hlint/badge/lts?label=Stackage)](https://www.stackage.org/package/hlint)

**Comment by zudov** [comment]
That's interesting. To me it reads `Stackage | 1.9.31`. Even in your message.

I curled `https://www.stackage.org/package/hlint/badge/lts?label=Stackage` and after some gazing at the returned xml I can confirm that stackage replies with correct badge.

There are some middlemen who are likely to be causing this problem:

- Github's caches. Here is the [url][github-cached-badge] which github puts in the rendered version of hlint's README (at least for me). However it also reads as `Stackage | 1.9.31`.
- Browser caches. Well, try to clean them or force-reload.
- ISP caches.

[github-cached-badge]: https://camo.githubusercontent.com/87f896d94f3ba26f115312501af838c2274f173d/68747470733a2f2f7777772e737461636b6167652e6f72672f7061636b6167652f686c696e742f62616467652f6c74733f6c6162656c3d537461636b616765

IIRC, it's not the first time when we encounter similar issues, so I think we should add the headers which would help those guys at invalidating their caches properly.

**Comment by zudov** [comment]
Here is the relevant issue https://github.com/github/markup/issues/224, I remember reading that before, but I absolutely forgot to take care of it.

**Comment by zudov** [comment]
Hmm. It seems that I actually did try to take care of it https://github.com/fpco/stackage-server/pull/141. Seems like it wasn't enough, adding `ETag` header would make a lot of sense. Travis and some other services also set `Pragma: no-cache` but I guess in our case we wouldn't mind some caching as long as ttl is a few hours.

**Comment by juhp** [comment]
Ah right I see what you mean - github caches images put in wiki markup right.

**Comment by juhp** [comment]
The image for the badge I see is: https://camo.githubusercontent.com/87f896d94f3ba26f115312501af838c2274f173d/68747470733a2f2f7777772e737461636b6167652e6f72672f7061636b6167652f686c696e742f62616467652f6c74733f6c6162656c3d537461636b616765

**Comment by chrisdone** [comment]
@juhp is this still happening?

**Comment by juhp** [comment]
Looks okay to me now, thanks - though I haven't checked now very extensively.
