### ISSUE TITLE
Display links to packages and/or changelogs on diff

### ISSUE THREAD

**Issue by charles-cooper** [fpco/stackage-server#166]
It would be helpful when reviewing snapshot diffs (e.g. https://www.stackage.org/diff/lts-5.12/lts-5.13) to have hyperlinks to either the packages or the relevant changelogs on either side, that way it is easier to review what changed in each individual package.

**Comment by snoyberg** [comment]
I don't see a problem. Interested in trying your hand at a pull request?

**Comment by charles-cooper** [comment]
Great! I can give it a try sometime this week.

**Comment by mgsloan** [comment]
A little off the main topic, but it'd also be cool to have something like [hdiff](http://hdiff.luite.com/), but giving source diffs between a particular selection of snapshots.  Potentially a feature to add to hdiff itself.  Not sure if it lets me diff non-consecutive versions out of the box.

Getting even cooler, imagine something that could concatenate together these diffs, but only for packages you depend on.  The ultimate thing like this would be "stack diff config1.yaml config2.yaml`, or something like that.  This would allow you to very easily review all changes that might affect your project.
