### ISSUE TITLE
Style up the haddock pages to match haskell-lang

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-server#170]
FIXME's here provide a way to achieve that on existing haddocks:

https://github.com/fpco/stackage-server/commit/60af396f9c769114de59226963b151a35ab34ee2#diff-3575859d62885096be97934a89513efaR1

This way we don't have to modify haddock past or present.

**Comment by mgsloan** [comment]
It would be great to have haddocks that weren't screen width.  Hard to read paragraphs of text that fit a bunch of sentences on a single line!

**Comment by chrisdone** [comment]
This is done and deployed.
