### ISSUE TITLE
Drop cabal information from stackage.org

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-server#171]
Or add classes around it so that we can drop it for use in haskell-lang. Stack has enough of a portion of Haskell users, with very few that use both stackage and cabal (and they don't need instructions).

**Comment by DanBurton** [comment]
What exactly are you suggesting to be dropped? The cabal.config link & instructions? Or something more?

**Comment by kosmikus** [comment]
This seems to have already been committed? https://github.com/fpco/stackage-server/commit/e0f8755f95a8f6987da70a88d39920d5c4564158

I fail to understand why this is an enhancement. The config files are very useful for me when I want to provide Stackage compatibility for my code, and without the links, I don't see how I would know that they're there / where they are.

I don't understand the comment that stackage/cabal users don't need instructions.

I could understand if the link was moved to a less prominent place. But why does it have to be removed completely?
