### ISSUE TITLE
stackage.org is really slow

### ISSUE THREAD

**Issue by MaxGabriel** [fpco/stackage-server#172]
I'm finding stackage.org really slow to load, both for regular results like the front page, as well as hoogle search results. Do other people experience this as well? Is the server just overloaded? I could potentially help improve this, but figured I should ask about it first.

Front page:

```
Max@maximilians-mbp /tmp> curl "https://www.stackage.org/" > test.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9359  100  9359    0     0    687      0  0:00:13  0:00:13 --:--:--  2562
```

Searching hoogle:

```
Max@maximilians-mbp /tmp> curl "https://www.stackage.org/lts-5.15/hoogle?q=%5Ba%5D+-%3E+a+-%3E+Bool" > search.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13478  100 13478    0     0    783      0  0:00:17  0:00:17 --:--:--  4176
```

**Comment by mgsloan** [comment]
I get similar timings for hoogle (not sure there's much we can do about that, directly).  For `stackage.org` I get 0.7 seconds.

**Comment by MaxGabriel** [comment]
Ah ok, my `stackage.org` timings are sub-second now as well. Is the hoogle slowness just a limitation of hoogle searching speed?

**Comment by mgsloan** [comment]
I'd imagine so, yes, probably because we're searching the whole set.

**Comment by rvion** [comment]
that's strage. hoogle used to be much faster before, and I don't think the package number increase is proportional to the slowdown. 
maybe hoogle speed don't decrease linearly with the size of its db ?
maybe the workload on stackage / hoogle is bigger that what it use to be with the growing popularity of stack ?

**Comment by nh2** [comment]
For me, stackage.org's homepage loads in sub-second time, and that hoogle query took 21 seconds.

**Comment by borsboom** [comment]
I looked at the clusters' server metrics, and they don't look overloaded, tending to hover around 50% CPU utilization without much in the way of spikes.  I'll try bumping it to three replicas on each cluster (for a total of 6) and see if that makes a difference.  Currently the nodes are running on m3.medium instances, but we could potentially try making those larger as well.

**Comment by borsboom** [comment]
I've done some more testing, and I run hoogle queries like the slow one above, I can watch the stackage-server process pin a core the whole time, so not too surprising that the amount of observed can vary widely, as it will very much depend on the overall load on the nodes, and when it takes this long to return results, it will be common for multiple hoogle requests to be happening at the same time.   So I guess we could throw more hardware at it, but better would be to figure out why this hoogle query is pinning a core for 15 seconds and optimize it.

**Comment by snoyberg** [comment]
I've pushed two minor tweaks to the Hoogle handling:

* It will only count up to 20 entries, avoiding the need to force extra results when they aren't needed for display
* Each server process will only answer one Hoogle query at a time, hopefully preventing the rest of the site from being slow

I'm deploying now, let's see if this helps

**Comment by rvion** [comment]
@snoyberg just tested , and it doesn't seem to be better on my side.
I'll test again in a few hours

**Comment by snoyberg** [comment]
It's not deployed yet

**Comment by snoyberg** [comment]
Alright, the change is deployed. I'm not seeing a major improvement on the Hoogle page load time, but the rest of the site at least seems like it remains more reliably responsive.

@ndmitchell: Do you have any input on high CPU usage when performing Hoogle queries?

**Comment by ndmitchell** [comment]
You guys are on Hoogle 4. The prototype Hoogle 5 at http://hoogle.haskell.org/ is dead fast, on a very underpowered server, albeit with a few less features. I should really finish it up and we can roll it out.

For info, some specific Hoogle 4 searches can be really slow (bad asymptotics) so they will always take a while.

**Comment by chrisdone** [comment]
Hoogle5 is deployed, and we also changed the deployment of stackage.org itself which significantly speeded up the site in general.

```
Chriss-MBP:~ chris$ curl "https://www.stackage.org/lts-5.15/hoogle?q=%5Ba%5D+-%3E+a+-%3E+Bool" > search.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4070  100  4070    0     0   3002      0  0:00:01  0:00:01 --:--:--  3003
```

**Comment by albertnetymk** [comment]
The above curl query is super fast for me as well. However, the following one takes 30 seconds.

```
$ curl "https://www.stackage.org/haddock/lts-9.17/base-4.9.1.0/Prelude.html#t:Functor" > search.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2953k  100 2953k    0     0  97711      0  0:00:30  0:00:30 --:--:--  677k
```

**Comment by mgsloan** [comment]
@albertnetymk Ah, interesting!  Yes, I also noticed that things were quite slow recently.  I can reproduce the problem.  I've mentioned it in our internal channels, but also pinging @snoyberg and @borsboom

**Comment by snoyberg** [comment]
Thank you for the report @albertnetymk, I've temporarily disabled the code that was slowing this down in 75390181c1ebf67e80766b9f69108e4d67df1b51

**Comment by albertnetymk** [comment]
Thank you very much. It's working fine now.

**Comment by hsyl20** [comment]
I also experience huge slowdowns. According to the `x-envoy-upstream-service-time` header, the time spent (~1min40) to serve a hoogle query isn't a network issue.

![image](https://user-images.githubusercontent.com/96633/91835471-b7e18780-ec49-11ea-924d-a6bd800203bc.png)
