### ISSUE TITLE
Installation instruction: Confusing Windows users

### ISSUE THREAD

**Issue by NCrashed** [fpco/stackage-server#173]
Several people were already caught up by the issue:

1. Google [haskell stack windows](https://www.google.com/search?q=stack+haskell+windows)
2. Go to the first match `Haskell Installation Instructions :: Stackage Server`
3. Don't read text body, scroll to `Windows` section (most users don't read unclear deprecation note at tope)
4. Go to [more information](https://github.com/fpco/minghc#readme) at MiniGHC download link.
5. Wonder that MiniGHC is deprecated and recommends to install stack, but stack recommends to install MiniGHC.

**Comment by snoyberg** [comment]
Pinging @chrisdone. We're currently working on some improved installation instructions, which will be hosted on haskell-lang.org. We should probably just have /install redirect to that new page when available.

In the meanwhile, I don't see anything wrong with removing the "alternative" content from /install. Want to send a PR? Relevant content is at: https://github.com/fpco/stackage-content/blob/master/install.md

**Comment by NCrashed** [comment]
Done.

**Comment by snoyberg** [comment]
Thanks, merged.
