### ISSUE TITLE
Intermittent 502 Bad Gateway response

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-server#175]
I'm getting occasional 502 Bad Gateway responses from https://www.stackage.org today.

**Comment by snoyberg** [comment]
I forgot to post: I kicked the server, and I haven't seen the issues since then. Pinging @borsboom

**Comment by snoyberg** [comment]
You OK if I close this issue, since the problem seems to be resolved for now?

**Comment by DanBurton** [comment]
Sure.
