### ISSUE TITLE
Fix the Haddock mangling code

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#176]
The current code in Handler.Haddock badly mangles the HTML, since it uses a function (showToken) from tagstream-conduit which doesn't properly escape HTML entities. This should be fixed, either by reimplementing `showToken` locally, converting the tokens to xml-conduit's `Event` type, or something similar.

**Comment by AndrewRademacher** [comment]
@mgsloan provided supporting example cases for this issue. The mangling can be observed in the identifier names from the module listed below. Both the source and Haddock pages are provided.

- [Source](https://s3.amazonaws.com/haddock.stackage.org/lts-5.17/base-unicode-symbols-0.2.2.4/src/Control-Applicative-Unicode.html#%229B)
- [Haddock](https://s3.amazonaws.com/haddock.stackage.org/lts-5.17/base-unicode-symbols-0.2.2.4/Control-Applicative-Unicode.html)

**Comment by mgsloan** [comment]
I'm actually not 100% sure that it's the mangling described here.  But it is certainly some variety of mangling, either at the haddock level or stackage-server.

**Comment by snoyberg** [comment]
That's not the problem under discussion. The issue under discussion is that HTML entities, especially in code examples, are not being escaped. If you look at the comments in Handler.Haddock, you'll see that this code path is currently disabled.
