### ISSUE TITLE
Hackage version wrong on package page

### ISSUE THREAD

**Issue by phadej** [fpco/stackage-server#177]
e.g. https://www.stackage.org/lts-2.22/package/case-insensitive-1.2.0.4 or https://www.stackage.org/lts-2.22/package/ad-4.2.3, Seems to show the version in the snapshot viewed.

<img width="465" alt="screen shot 2016-05-17 at 18 04 11" src="https://cloud.githubusercontent.com/assets/51087/15327363/e1ab9e94-1c59-11e6-8493-86abd9bbd8df.png">

**Comment by snoyberg** [comment]
Pinging @juhp 

Yeah, it's showing the current version on this page, not the most recent version available on Hackage. I'm not sure what the desired display would look like.

**Comment by phadej** [comment]
The current version should definitely be on the page (maybe in title or as a subtitle),
but the latest version (i.e. the one on Hackage) is interesting information as well.

**Comment by snoyberg** [comment]
I've just pushed a commit that should fix this, though I'm not convinced it's the optimal display. There are now four different versions that can appear on the page:

* Current version being displayed (none if the package is not in any snapshot)
* Version in latest LTS if available
* Version in latest Nightly if available
* Most recent version from Hackage

I pushed this change to the `prod` branch, so the newly-set-up CI job should deploy it to the live site once the build completes (it has an empty cache right now, so it may take some time).

**Comment by juhp** [comment]
Thanks Michael, I agree - i actually noticed this a little while back but I didn't get round to reporting or looking into it. I will try to find some time soon to look into it more and get the right version on the page.

**Comment by snoyberg** [comment]
For the record, I've already pushed some updates, though further improvements are definitely welcome.

**Comment by snoyberg** [comment]
I think this is resolved, closing. If something still needs to be done, please reopen.
