### ISSUE TITLE
The cabal.config option does not work

### ISSUE THREAD

**Issue by carldong** [fpco/stackage-server#179]
I am using Haskell Platform 7.10.3 for now, and I am trying the cabal install using `cabal.config` provided in <stackage.org>, and I get this when I do `cabal update`:

     Unrecognized field constraints on line 5

**Comment by carldong** [comment]
Seems like if I manually change every line to 

    constraint: (something)

then `cabal update` does not report error. I hope that means it works this way

**Comment by snoyberg** [comment]
Are you trying to use the local config file in the global location? Note that there are two difference versions, e.g.:

https://www.stackage.org/lts-5.17/cabal.config

vs

https://www.stackage.org/lts-5.17/cabal.config?global=true

**Comment by carldong** [comment]
Oh, I see. However, the Stackage site does not mention this, I believe

**Comment by snoyberg** [comment]
It does mention both there local and global configurations on each snapshot
page, with links to the appropriate files.

**Comment by carldong** [comment]
Ah, I found it. Missed that line for many times.
