### ISSUE TITLE
Package page inconsistent

### ISSUE THREAD

**Issue by pypingou** [fpco/stackage-server#182]
The version displayed on the package page are inconsistent, it's like one of the server isn't running the same code as the others.

Belong are two screenshot of https://www.stackage.org/package/aeson taken right now with just a few 'refresh' in between:

![screenshot from 2016-06-14 12-08-35](https://cloud.githubusercontent.com/assets/1240038/16039254/03e2253e-3229-11e6-8159-fc2fd138f31f.png)
![screenshot from 2016-06-14 12-08-41](https://cloud.githubusercontent.com/assets/1240038/16039255/03e34c66-3229-11e6-91e1-8ee3e41e0bc1.png)

**Comment by pypingou** [comment]
This breaks the stackage plugin for https://release-monitoring.org

**Comment by snoyberg** [comment]
It was a failed deployment, it should be fixed now

**Comment by pypingou** [comment]
Thanks :)
