### ISSUE TITLE
build output should indicate when a package is coming from upstream

### ISSUE THREAD

**Issue by simonmichael** [fpco/stackage-server#185]
When stack build is asked to install a package that's not local or in a snapshot, it can fetch it from upstream/Hackage, which looks like this:
```shell
~$ stack install tabular
Run from outside a project, using implicit global project config
Using resolver: lts-6.0 from implicit global project's config file: /Users/simon/.stack/global/stack.yaml
tabular-0.2.2.7: configure
tabular-0.2.2.7: build
tabular-0.2.2.7: copy/register
```
I found this rather confusing, assuming it meant the package was being fetched from the lts-6.0 snapshot (cf https://github.com/fpco/stackage-server/issues/184). An explicit "package fetched from hackage" message would also help to combat the (not uncommon, I guess) mistake of assuming stack only fetches from stackage.

**Comment by snoyberg** [comment]
This was probably intended as an issue against Stack, not stackage-server.

**Comment by chrisdone** [comment]
@simonmichael Can you open an issue in stack? Cheers!

**Comment by simonmichael** [comment]
Done, thanks.
