### ISSUE TITLE
foldr in base appears on page 4 of Hoogle

### ISSUE THREAD

**Issue by tomjaguarpaw** [fpco/stackage-server#186]
Currently I have to scroll to page 4 before I find the definition of `foldr` from `base`.  It should be the first result!

https://www.stackage.org/lts-6.3/hoogle?q=foldr&page=4

**Comment by chrisdone** [comment]
Thanks for the report, this is an artifact of upgrading to hoogle 5, I'm not sure what's causing this ordering at the moment.

**Comment by chrisdone** [comment]
Closing as dupe of #183. Bump again if I've misjudged.
