### ISSUE TITLE
Design of Haddock docs 

### ISSUE THREAD

**Issue by nd2s** [fpco/stackage-server#188]
I'm sorry, but I find the current CSS style of the Haddock documentation on stackage.org horrible. It's impossible to work with. There is almost no contrast, everything looks the same, and it takes up more space than the Hackage one (which makes it less overseeable). I can't even see what's linked and what not.

Any chance the standard-Haddock/Hackage one will return?

**Comment by snoyberg** [comment]
This tone on a clearly subjective topic is unlikely going to make contributors amenable to making changes. Perhaps you'd be interested in sending a PR to give the user an option to disable the modified styling via a query string parameter or cookie?

As a personal vote, I find the newer styling easier on the eyes and the more reliable table of contents make it much easier to navigate.

**Comment by nd2s** [comment]
Oh, looks like Github forgot to notify me about your reply.

Sorry, this wasn't meant to be rude.
Except for the I-find-it-horrible part, I don't find this that subjective, though. Lower contrast is objectively harder to read.

I'll look into it, maybe I can come up with a quick (and clean) solution.

**Comment by chreekat** [comment]
Here's something that I hope we can agree is objectively bad:

![image](https://cloud.githubusercontent.com/assets/538538/16613686/0cb51d52-4376-11e6-8ff8-386d3c067c92.png)

On Hackage, this is:

![image](https://cloud.githubusercontent.com/assets/538538/16613802/91603046-4376-11e6-859e-ba90473d6e4a.png)

Pros of the Hackage version:
* easy-to-discern links in the types
* clear distinction between types and Haddocks
* a punt on good line lengths by not wrapping at all (questionable ;) )

I'm also not sure what the most standout word here ("Arguments") is even doing there. Especially in this bigger picture:

![image](https://cloud.githubusercontent.com/assets/538538/16613913/2b5b48fc-4377-11e6-948d-a5ae8c29cf69.png)

"Methods" is presumably a subheading for the PersistUnique typeclass, but it's the same size and position as "Arguments", which is a subheading for one of the methods.

So my concrete suggestions:

* Make "Methods" stand out more than "Arguments"
* Make "Arguments" stand out *less* than the name of the method it belongs to
* Let type parameters and argument types stretch further, perhaps by vertically offsetting the lines from their haddocks?
* Put the method's haddocks before the "Arguments" block. At least that way it won't look like the "Arguments" is the heading for the entire chunk of documentation.

**Comment by jtojnar** [comment]
I am more concerned about syntax highlighting – for me, the page looks almost as if there was not any. Only after closer inspection, I notice the subtle differences in hues. This defeats the whole purpose of the highlighting (easier navigation in the code without having to focus on the code itself).

And I still have quite good colour vision, I cannot even imagine how it must feel for less fortunate people. I would definitely appreciate greater contrast between the different colours.

**Comment by chrisdone** [comment]
Summarizing the points into some proposed action items:

1. Remove the "arguments" keyword in general - it's distracting, obvious and can be hidden with CSS.
2. Make the colours for links stand out more with higher contrast.
3. Pop a background colour on the type part of docs like Hackage.

I might get round to applying these this week, but someone else is free to tackle them meanwhile. Just post a comment saying so to avoid feet stepping.

**Comment by chrisdone** [comment]
The example page used in discussion was: https://www.stackage.org/haddock/lts-6.7/persistent-2.2.4.1/Database-Persist-Class.html

**Comment by chrisdone** [comment]
Opened a PR to fix this. This reverts the style back to regular Hackage but with just the color theme of HL.

<img width="853" alt="screenshot 2016-08-23 17 50 34" src="https://cloud.githubusercontent.com/assets/11019/17899071/5abf894c-695a-11e6-9b70-c726c1a385db.png">

**Comment by chrisdone** [comment]
Deployed to production: https://www.stackage.org/haddock/lts-6.7/persistent-2.2.4.1/Database-Persist-Class.html

**Comment by chrisdone** [comment]
If that's not legible we can make the blue bolder or something.

**Comment by kim** [comment]
@chrisdone why was the change reverted (#197)? I found it a huge improvement...

**Comment by rvion** [comment]
same question here
