### ISSUE TITLE
Feature request: show repository and commit hash for each package

### ISSUE THREAD

**Issue by AaronFriel** [fpco/stackage-server#189]
Good example:

I want to modify my local version of `yesod`, without introducing too many variables and potentially upstreaming any changes. So I check, I'm on `lts-6.4`, so I find this: https://www.stackage.org/lts-6.4/package/yesod-1.4.3

How do I clone yesod 1.4.3 so that I'm working with the same source, to ensure I don't introduce a subtle bug by pulling from `HEAD`?

(Note: In this case 1.4.3 is HEAD, but without going to GitHub, it's not easy to figure out!)

**Comment by bergmark** [comment]
A `source-repository` section in the cabal file can be used to point to a tag for the release, but pretty much no one uses this feature as it's not automated. The safe way would be to just use the release tarballs.

**Comment by chrisdone** [comment]
As @bergmark said, there's no reliable relationship tracked in .cabal files and their git hash.

However, you can use `stack unpack`! 😀 

```
$ mkdir demo
$ cd demo
$ echo 'resolver: lts-6.4' > stack.yaml
$ stack unpack yesod
Unpacked yesod-1.4.3 to /Users/chris/demo/yesod-1.4.3/
```

:metal:
