### ISSUE TITLE
Are the hoogle .txt files available?

### ISSUE THREAD

**Issue by erantapaa** [fpco/stackage-server#195]
Are the individual hoogle .txt files available for each package?

IIRC, the complete compiled hoogle database for a resolver is available (although I can't remember how to access at the moment), but I'm interested in the raw .txt files.

**Comment by chrisdone** [comment]
I don't think that's currently exposed. I'm curious, what's your use-case?

**Comment by chrisdone** [comment]
The upcoming `stack hoogle` _may_ be of interest depending on your use-case.

**Comment by erantapaa** [comment]
It would just be nice to get the hoogle index files without having to build all of Stackage - i.e. much like you can get the index files from Hackage via http://hackage.haskell.org/packages/hoogle.tar.gz

My use case right now is just experimentation with alternative ways of querying / displaying that information. Since you are building those files anyway, perhaps it can made available
at some canonical url.

That said, is the compiled Hoogle database for a resolver available someplace? I seem to recall that there was, but I don't see the link for it anymore.
