### ISSUE TITLE
Missing ubuntu-mono font

### ISSUE THREAD

**Issue by mitchellwrosen** [fpco/stackage-server#199]
`<pre>` tags are styled with

```
font-family: "ubuntu mono", "Monaco" !important;
```

but I don't have this font installed, so code blocks are being rendered in some non-monospaced default font. Is there any way to instead fall back on a `font-family: monospaced` instead?

**Comment by qrilka** [comment]
This one is big argument to prefer hackage haddocks over ones from stackage, at least for me

**Comment by snoyberg** [comment]
Chris is on vacation, but I can probably push a fix later today. If someone
wants to send a PR to include a better monospace fallback, I'll be able to
merge that pretty quickly.

**Comment by qrilka** [comment]
@snoyberg any pointers to the CI server where I could check that?

**Comment by snoyberg** [comment]
Forgot to copy-paste the link, sorry. https://ci.stackage.org

**Comment by qrilka** [comment]
That's much better, thanks @snoyberg

**Comment by snoyberg** [comment]
Cool, I just merged to prod. If in the future you notice possible CSS improvements, don't hesitate to send a PR.

**Comment by qrilka** [comment]
But @snoyberg there is #200 already

**Comment by snoyberg** [comment]
I didn't see that, I don't actively monitor this repo usually. I'd have
gone with that instead.

**Comment by chrisdone** [comment]
👍
