### ISSUE TITLE
Add sitemap.xml file

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#20]
We should give higher priority for homepage and package pages vs individual documentation pages.

**Comment by snoyberg** [comment]
We may want to go farther and have robots.txt ban documentation pages. This would also prevent crawlers from forcing us to do a lot of unpacking.

**Comment by DanBurton** [comment]
How many of our URLs do we want to be in the sitemap? Should we be dynamically performing DB queries to generate the sitemap upon request?

**Comment by snoyberg** [comment]
Yes, performing queries makes sense. I wouldn't include individually Haddock documentation pages most likely, but certainly homepage, relevant static content pages like installation instructions, /lts, and /nightly.

**Comment by DanBurton** [comment]
I've created PR #84. @chrisdone please review.
