### ISSUE TITLE
Reduce some transparency on synopsis section

### ISSUE THREAD

**Issue by psibi** [fpco/stackage-server#202]
Right now there are situations like this:

![stack-bug](https://cloud.githubusercontent.com/assets/737477/18833625/3d4cbeaa-840f-11e6-9cbd-aa355e12bf58.png)

**Comment by snoyberg** [comment]
Good catch. Does that look better?
https://ci.stackage.org/haddock/lts-6.1/base-4.8.2.0/Text-ParserCombinators-ReadP.html

**Comment by psibi** [comment]
Thanks, that is perfect. :+1:

**Comment by snoyberg** [comment]
Cool, pushed to prod, it should deploy in the next 5 minutes or so.
