### ISSUE TITLE
stackage-lts-2.14 does not exist

### ISSUE THREAD

**Issue by TamaHobbit** [fpco/stackage-server#203]
I'm trying to build the [Empiresmod website](https://github.com/EmpiresCommunity/website). It was built using a long term service stackage package, for which [the link still seems to work.](https://www.stackage.org/lts-2.14) And yet, attempting to use it by running cabal build fails, stating the package list for 'stackage-lts-2.14' does not exist.

```
$ cabal build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Warning: The package list for 'stackage-lts-2.14' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Configuring empires-0.1.0.0...
cabal: At least the following dependencies are missing:
hakyll ==4.6.*
```

**Comment by snoyberg** [comment]
Did you run `cabal update` as suggested?

**Comment by TamaHobbit** [comment]
Yes; that didn't change anything. 

It seems to work when I use stack build though - I don't really know why cabal would be necessary at all.

**Comment by snoyberg** [comment]
It's possible that with an LTS that old, the original docs were written
before Stack was released. Maybe send them a PR to recommend using Stack
for installation instead?
