### ISSUE TITLE
Temporary "openFile: resource busy (file is locked)" from Hoogle search

### ISSUE THREAD

**Issue by Blaisorblade** [fpco/stackage-server#206]
Just got, from https://www.stackage.org/lts-7.0/hoogle?q=elem&exact=on, the following text
```
hoogle/lts-7.0/5.0.hoo.tmp: openFile: resource busy (file is locked)
```
This was transitory, but I thought maybe you'd wanna know. Feel free to close if that's as intended.

**Comment by snoyberg** [comment]
I'm putting in some more advanced locking behavior to ensure only one thread at a time is working on a file. I have a feeling I should generalize this logic into a library somehow...

**Comment by snoyberg** [comment]
OK, I've just pushed a commit for master with this logic. A code review would be welcome actually :) d2f2e15

**Comment by DanBurton** [comment]
My review: https://github.com/fpco/stackage-server/commit/d2f2e1537fb879e7ec81800f0b438c4f2115ad22#commitcomment-19440622

The approach LGTM.

**Comment by Blaisorblade** [comment]
Wow, thanks for the prompt response, I'm impressed! You just ensured I'll probably report such things again next time!

**Comment by snoyberg** [comment]
Closing on the assumption the fix I wrote actually solves this. If we see it again, let's reopen.

**Comment by snoyberg** [comment]
I've added a new module, `Control.SingleRun`, that captures this logic. I avoided using STM or containers so it could theoretically be added to auto-update if desired.

**Comment by snoyberg** [comment]
Sorry, forgot to add the commit link: 37d7a52

**Comment by snoyberg** [comment]
Nope, I'm still an idiot: b5f562a
