### ISSUE TITLE
Latest LTS for a given GHC version

### ISSUE THREAD

**Issue by ozgurakgun** [fpco/stackage-server#210]
(Moving from fpco/stackage#1955)

> How would one find what the latest LTS is for a given GHC version? My use case is wanting to support GHCs 7.8.4, 7.10.3, 8.0.1 at the same time.
> 
> Currently I need to browse the snapshots page manually to find the latest LTS for 7.8.4 for example. The answer is on the 9th page!
> 8.0.1 and 7.10.3 happen to be easier, since they were updated recently.
> 
> It would be nice if there was an easier way of finding out this information. Maybe the stack tool can be taught to answer the question?

**Comment by snoyberg** [comment]
This is deployed to the CI server, can you check it out? https://ci.stackage.org/

**Comment by ozgurakgun** [comment]
Looks great @snoyberg, thanks!
