### ISSUE TITLE
Feature request: Redirect to latest lts by default when no lts version is specified

### ISSUE THREAD

**Issue by psibi** [fpco/stackage-server#212]
The following URL

https://www.stackage.org/haddock/lts-7.0/http-client/Network-HTTP-Client.html

redirects to a proper version of http-client within that lts:

https://www.stackage.org/haddock/lts-7.0/http-client-0.4.31.1/Network-HTTP-Client.html

But the following doesn't work:

https://www.stackage.org/haddock/lts/http-client/Network-HTTP-Client.html

It would be nice if this url can resolve to the latest lts if no version is specified.

Usecase: I need it for the [browser plugin](https://github.com/psibi/stackgo) I'm using. Right now, I have to release a frequent update to the plugin with the updated lts to catch up with Stackage.

**Comment by snoyberg** [comment]
Great idea! Can you test this out on the CI server?

https://ci.stackage.org/haddock/lts/http-client/Network-HTTP-Client.html

**Comment by psibi** [comment]
Thanks, works as expected.

**Comment by snoyberg** [comment]
Cool!
