### ISSUE TITLE
Fix the ordering of the hoogle results

### ISSUE THREAD

**Issue by BartAdv** [fpco/stackage-server#214]
Following the reddit comment thread: https://m.reddit.com/r/haskell/comments/5e8ptf/comment/daaryjb

Right now, the results seem to be sorted alphabetically, which, for example gives Agda as first result when searching for `<$>`. Sorting by number of reverse dependencies could be a possible option for more meaningful results.

**Comment by snoyberg** [comment]
@ndmitchell Is there any guarantee on the order of results from Hoogle, or any way to influence the order in which results come back?

**Comment by ndmitchell** [comment]
See http://hoogle.haskell.org/?hoogle=%3C%24%3E&scope=set%3Astackage which gets it right because it does sort by reverse dependencies. You are on Hoogle 5, right? Question is if the information isn't in the Hoogle database, or if it's being lost after that.

**Comment by snoyberg** [comment]
Yes, but we're specifically using this commit:

https://github.com/snoyberg/hoogle/tree/765bd653d687e8569cd989be1637de86dcb20d56

Was the functionality added after that commit?

**Comment by ndmitchell** [comment]
That links to Hoogle 4, which doesn't have that feature.

**Comment by snoyberg** [comment]
The .cabal file calls it version 5.0:

https://github.com/snoyberg/hoogle/blob/765bd653d687e8569cd989be1637de86dcb20d56/hoogle.cabal#L4

But I can try bumping to a newer commit (or just the released version on Hackage). Downside is it will invalidate all existing Hoogle DBs, but with the faster generation I can probably start allowing it to regenerate more DBs than it has in the past. I'll probably kick that off on Sunday.

**Comment by ndmitchell** [comment]
I followed the first link on a mobile, and it definitely didn't end up where it does from a desktop.

I am pretty sure that version has the popularity thing in it - but upgrading seems like a good idea anyway - if there's a bug impacting you it's much easier to figure out from the latest code rather than old code. Is the Hoogle database available for download? That would let me see if it's a bug in your UI side (after the database), or generation side (baked into the database).

**Comment by snoyberg** [comment]
@ndmitchell Thanks, there's an 85mb 5.0 database for LTS 7.9 at:

https://s3.amazonaws.com/haddock.stackage.org/hoogle/lts-7.9/5.0.hoo

I'm going to try deploying the upgrade soon.

**Comment by snoyberg** [comment]
And here's a database generated for 5.0.5:

https://s3.amazonaws.com/haddock.stackage.org/hoogle/lts-7.10/5.0.5.hoo

Results don't look any better:

https://ci.stackage.org/lts-7.10/hoogle?q=%3C%24%3E

**Comment by snoyberg** [comment]
And final comment before I stop spamming for the night, relevant code for generating the Hoogle DBs: https://github.com/fpco/stackage-server/blob/master/Stackage/Database/Cron.hs#L215

**Comment by ndmitchell** [comment]
Hoogle 5 always writes out the version number, in plain text, at both the beginning and end of the database, as a sanity check and to give good error messages. A database I generate with 5.0.5 has "HOOGLE-5.0.5" at both the start and end. None of your databases do. Is that something you're deliberately stripping?

**Comment by snoyberg** [comment]
No, not to my knowledge, that's very strange. I can look into this more
tomorrow.

**Comment by snoyberg** [comment]
@ndmitchell I figured out the problem: the files are `.gz` compressed, and most likely the download method you're using (e.g., just plain `wget`) isn't decompressing it. It's a funny artifact of how we're storing things with S3. If I `gunzip` the file, I see HOOGLE-5.0.5 at the beginning.

**Comment by ndmitchell** [comment]
The order is wrong in the database. The reason is that `--local=dir` looks for `.txt` files which it uses for the Hoogle information, but doesn't read the `.cabal` files at all, so assumes everything is equally popular. When you are running `--local=dir` in your cron thing, are the `.cabal` files adjacent to the `.txt` files? Could they be? Having Hoogle make use of both files seems sensible.

**Comment by snoyberg** [comment]
Yeah, I can do that pretty easily I think (hope).

**Comment by snoyberg** [comment]
@ndmitchell I've made modifications to stackage-server-cron to place the .cabal files in the directory. Just to confirm: is the situation that Hoogle does not currently look for the .cabal files locally?

**Comment by snoyberg** [comment]
Alright, I think I got this figured out: https://github.com/ndmitchell/hoogle/pull/196

**Comment by snoyberg** [comment]
And sure enough, with this new logic in place:

https://ci.stackage.org/lts-7.11/hoogle?q=%3C%24%3E

@ndmitchell I'll hold off on deploying these changes until you're happy with that Hoogle PR instead of deploying off of my branch. Thanks for the support!

**Comment by ndmitchell** [comment]
I'm happy and have approved. Let me know if you want a release, or if working off a git hash makes no difference to you. Thanks a lot for the patches.

**Comment by snoyberg** [comment]
A release would be nice in this case actually, in case users want to be
able to use the Hoogle databases we're generating.

**Comment by ndmitchell** [comment]
Hoogle 5.0.6 has now been released.

**Comment by snoyberg** [comment]
Awesome, thanks!

**Comment by snoyberg** [comment]
I think we're all good now:

https://www.stackage.org/lts-7.11/hoogle?q=%3C%24%3E

@BartAdv mind giving it a check and confirming?

**Comment by BartAdv** [comment]
Yup, looks great now :)
