### ISSUE TITLE
top page listing latest lts7 as 7.0

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-server#216]
I noticed since yesterday that https://www.stackage.org/ under "Latest LTS per GHC version" now currently says:

* LTS 7.0 for GHC 8.0.1

even though the current LTS version is 7.12.

I didn't have time to look at the code or investigate but thought I would report this anyway.

**Comment by snoyberg** [comment]
Thanks, should be fixed.

**Comment by juhp** [comment]
Thank you
