### ISSUE TITLE
snapshot incorrect hours ago

### ISSUE THREAD

**Issue by juhp** [fpco/stackage-server#217]
This is a minor thing and I didn't have time to investigate yet but I noticed and thought I would report that the Snapshots column on the right side of http://stackage.org/ seems to show an incorrect number of hours ago for today's latest snapshot.

Eg lts-7.13 was uploaded about 1.5 hours ago but the website says "5 hours ago": maybe it is off by timezone??

**Comment by snoyberg** [comment]
It should just say days, we don't actually try to track time of day information, and it's just assuming midnight.

**Comment by juhp** [comment]
Thought i had posted a comment earlier... anyway looks good now thanks!
