### ISSUE TITLE
Images in diagrams not displayed

### ISSUE THREAD

**Issue by k-bx** [fpco/stackage-server#218]
I just did `stack init; stack haddock` on latest `diagrams-lib` sources and images are rendered fine locally, but they are absent on stackage. See [an example](https://www.stackage.org/haddock/lts-7.14/diagrams-lib-1.3.1.4/Diagrams-TwoD.html#v:triangle).

**Comment by snoyberg** [comment]
I've just pushed a tweak that may address this to the stackage-curator repo, let's see if it's fixed in the next nightly upload.

**Comment by k-bx** [comment]
@snoyberg yay, it's fixed, thank you! https://www.stackage.org/haddock/nightly-2016-12-28/diagrams-lib-1.4.0.1/Diagrams-TwoD.html#v:arcBetween
