### ISSUE TITLE
Synopsis missing in latest haddocks

### ISSUE THREAD

**Issue by psibi** [fpco/stackage-server#222]
This used to be present previously in haddock:

![synopsis](https://cloud.githubusercontent.com/assets/737477/23227588/6d0ab884-f95f-11e6-90cc-567f0d0a3bc2.png)

Previous working url: https://www.stackage.org/haddock/lts-7.19/base-4.9.0.0/Control-Applicative.html
Latest non-working url: https://www.stackage.org/haddock/lts-8.2/base-4.9.1.0/Control-Applicative.html

**Comment by snoyberg** [comment]
I think this is an upstream change at GHC or Haddock itself, as I'm reproducing that difference with my local GHC-provided HTML docs.

<img width="1239" alt="screen shot 2017-02-23 at 8 09 22 am" src="https://cloud.githubusercontent.com/assets/49415/23246884/7c80b9f4-f99f-11e6-988b-2738e533c031.png">

<img width="1243" alt="screen shot 2017-02-23 at 8 09 10 am" src="https://cloud.githubusercontent.com/assets/49415/23246890/83050848-f99f-11e6-8b03-63a7ee517e0e.png">

**Comment by psibi** [comment]
Yes, it's a upstream issue. It has been fixed in master: https://github.com/haskell/haddock/issues/599
Closing the issue.

**Comment by psibi** [comment]
This issue is fixed in upstream and Hackage seems to be producing fine but Stackage yet doesn't produce it: https://www.stackage.org/haddock/nightly-2018-01-09/persistent-2.7.1/Database-Persist.html

Whereas hackage is producing it: https://hackage.haskell.org/package/persistent-2.7.3/docs/Database-Persist.html

Both seem to be using the same version of Haddock for producing the pages.

**Comment by snoyberg** [comment]
It appears to be our custom styling, since adding `?style=plain` to the URL lets it appear:

https://www.stackage.org/haddock/nightly-2018-01-09/persistent-2.7.1/Database-Persist.html?style=plain

@chrisdone did you (or someone else) remove the synopsis bit intentionally?
