### ISSUE TITLE
Badges not updating?

### ISSUE THREAD

**Issue by quchen** [fpco/stackage-server#227]
The Stackage badge for [my package](https://github.com/quchen/prettyprinter/#a-modern-wadlerleijen-prettyprinter) does not seem to update, even though it is included in Stackage since the beginning of the week. Is this maybe a caching problem?

[![](https://www.stackage.org/package/prettyprinter/badge/lts?style=flat-square&label=Stackage&colorB=0a7bbb)](https://www.stackage.org/package/prettyprinter)

    [![](https://www.stackage.org/package/prettyprinter/badge/lts?style=flat-square&label=Stackage&colorB=0a7bbb)](https://www.stackage.org/package/prettyprinter)

**Comment by snoyberg** [comment]
Your package is not in lts-8, which is what your URL is asking for (the latest LTS). The following badges work, for example:

* ![](https://www.stackage.org/package/prettyprinter/badge/lts-6?style=flat-square&label=Stackage&colorB=0a7bbb)
* ![](https://www.stackage.org/package/prettyprinter/badge/nightly?style=flat-square&label=Stackage&colorB=0a7bbb)

**Comment by quchen** [comment]
Oh, I thought it was added in the last LTS release. Now that I look at [the ticket](https://github.com/fpco/lts-haskell/issues/57) is still open. I should have looked twice! Sorry about that.

**Comment by snoyberg** [comment]
No problem
