### ISSUE TITLE
Links to source code with fragment doesn't work for functions

### ISSUE THREAD

**Issue by lwm** [fpco/stackage-server#236]
Follows on from https://github.com/fpco/stackage/issues/2522:

> Example:
> https://www.stackage.org/haddock/lts-8.14/base-4.9.1.0/src/GHC-Base.html#fmap
> should open the page where fmap definition starts
> 
> I found the link here:
> https://www.stackage.org/haddock/lts-8.14/base-4.9.1.0/Data-Functor-Compose.html#t:Compose
> 
> However, it works for types:
> https://www.stackage.org/haddock/lts-8.14/base-4.9.1.0/src/Data-Functor-Compose.html#Compose

**Comment by snoyberg** [comment]
The HTML files being referred to ship with GHC itself, and—unless I'm missing something—no anchors exist in the HTML. I think this issue needs to be opened upstream with GHC or Haddock.

**Comment by lwm** [comment]
Hmmmm ... @ricksanchez, do you feel like moving this upstream to GHC/Haddock (whichever it is)?

Please re-open if there is something that needs to be done here!
