### ISSUE TITLE
Hoogle search fails

### ISSUE THREAD

**Issue by tfausak** [fpco/stackage-server#238]
Trying to search for anything returns an error. For example: https://www.stackage.org/lts-9.8/hoogle?q=spork

<img width="293" alt="screen shot 2017-10-12 at 9 20 31 am" src="https://user-images.githubusercontent.com/408753/31500996-ac48a3dc-af2e-11e7-8cf4-e52e58b7cf06.png">

> The given Hoogle database is not available.

**Comment by snoyberg** [comment]
It looks like Hoogle is crashing when creating the database. I'm looking into this. Thanks for the report.

**Comment by snoyberg** [comment]
I ran the cron job on my local machine, which generated correctly. This is looking more like a resource limit issue than, say, a bug in Hoogle. I'm bumping the memory and CPU limits on the cron job.

**Comment by snoyberg** [comment]
It looks like the increased limits have gotten it to work. I'm going to close the issue for now. If you notice problems again, please report.
