### ISSUE TITLE
Stackage.com haddock contrast is difficult to read

### ISSUE THREAD

**Issue by charles-cooper** [fpco/stackage-server#244]
Not sure how popular this will be but - while the availability of stackage documentation is **much** better than hackage, I find stackage.com haddocks more difficult to read than hackage because of the color scheme. This is the main reason I still prefer hackage documentation even though it is less available. Blue on blue on blue just doesn't provide enough contrast for my eyes (which are often tired from too much screen time!) to quickly make out links, names, etc. While this is clearly an aesthetic judgment, aesthetics are important to usability which is why I am opening this issue.

Is there anything that can be done about this?

**Comment by chrisdone** [comment]
Not a problem, I can increase the contrast more.

**Comment by chrisdone** [comment]
I've increased the contrast in e607494. Hope this is helpful. Hit Shift-Cmd-R to refresh the CSS on the site.

## Before/after top

<img width="1438" alt="screenshot 2017-12-04 10 55 35" src="https://user-images.githubusercontent.com/11019/33549269-de9e8392-d8e1-11e7-8f98-f0ae53a610be.png">

<img width="1440" alt="screenshot 2017-12-04 10 55 45" src="https://user-images.githubusercontent.com/11019/33549268-de8a48dc-d8e1-11e7-8670-7d622600cde1.png">

## Before/after headings

<img width="1438" alt="screenshot 2017-12-04 10 55 59" src="https://user-images.githubusercontent.com/11019/33549267-de73d8ea-d8e1-11e7-9573-2d6930979a78.png">

<img width="1440" alt="screenshot 2017-12-04 10 56 10" src="https://user-images.githubusercontent.com/11019/33549266-de5b3650-d8e1-11e7-89e5-8f4f77d31f2b.png">
