### ISSUE TITLE
Images in Haddock stylesheet are missing from S3

### ISSUE THREAD

**Issue by enolan** [fpco/stackage-server#245]
"hslogo-16.png" "minus.gif" and "plus.gif" aren't loading on the production site. Example [here](https://www.stackage.org/haddock/lts-9.2/aeson-1.1.2.0/Data-Aeson.html#g:7).

The URLs are:
- https://s3.amazonaws.com/haddock.stackage.org/byhash/hslogo-16.png
- https://s3.amazonaws.com/haddock.stackage.org/byhash/minus.gif
- https://s3.amazonaws.com/haddock.stackage.org/byhash/plus.gif

**Comment by snoyberg** [comment]
Thanks for the report, can you confirm that it's working now?

**Comment by enolan** [comment]
Yep, looks good.

Thanks Michael.

**Comment by snoyberg** [comment]
No problem, thanks for the report.
