### ISSUE TITLE
Request: Stable url for hoogle on latest LTS

### ISSUE THREAD

**Issue by JulianBirch** [fpco/stackage-server#250]
The search function on the front page of stackage is much more useful than the hoogle url, but it doesn't take you to a stable url (it updates each time a new lts drops). This prevents us from using it as a search engine within chrome (it'll work for a while, but the lts drops every so often and it won't track latest).

TL;DR; It would be nice if https://www.stackage.org/latest/hoogle?q=unfoldr was valid and the search box on the front page used it.

**Comment by snoyberg** [comment]
If you use https://www.stackage.org/lts/hoogle?q=unfoldr, it will
automatically redirect to the latest.
