### ISSUE TITLE
stackage.org reports wrong `base` version as "Latest on Hackage"

### ISSUE THREAD

**Issue by sjakobi** [fpco/stackage-server#252]
![bildschirmfoto vom 2018-03-10 00-45-14](https://user-images.githubusercontent.com/3664523/37235136-8d0cf228-23fc-11e8-99c0-48b38121fd16.png)

**Comment by snoyberg** [comment]
Thanks for the report. I've identified the problem, we just need to update the Cabal library being used. I'll hopefully be pushing out a fix in the next few hours.

**Comment by snoyberg** [comment]
Looks like it's working now, can you confirm?

**Comment by sjakobi** [comment]
Works now! Thanks! :)
