### ISSUE TITLE
License display could be improved

### ISSUE THREAD

**Issue by dbaynard** [fpco/stackage-server#259]
SPDX support for licenses is not quite right.

For example, [ucam-webauth-types](https://www.stackage.org/package/ucam-webauth-types) can be licensed under BSD3 or Apache 2.0.

The license field is described in hpack and cabal formats respectively, as

```yaml
license: BSD-3-Clause OR Apache-2.0
```

and

```cabal
license:        (BSD-3-Clause OR Apache-2.0)
```

This is then displayed on stackage (and packdeps.haskellers.com) as

> BSD3ClauseORApache20 licensed…

Hackage correctly displays this as

> #### License
> (BSD-3-Clause OR Apache-2.0)

**Comment by snoyberg** [comment]
I think I've addressed the problem in the code at https://github.com/commercialhaskell/all-cabal-tool/commit/114155a24483abc2954f4a4c4a8bb5ccc1130ac5. Now I just need to regenerate all of the files and get the changes onto Github so that Stackage Server can pick them up.

**Comment by snoyberg** [comment]
This should be displaying correctly now, can you confirm?

**Comment by snoyberg** [comment]
Yes, it did, and should be addressed now. Thanks for pointing that out too!

**Comment by dbaynard** [comment]
Great, that too. Thank you
