### ISSUE TITLE
Hoogle search broken for lts-14.7

### ISSUE THREAD

**Issue by vaclavsvejcar** [fpco/stackage-server#275]
<img width="1081" alt="Snímek obrazovky 2019-09-25 v 10 25 13" src="https://user-images.githubusercontent.com/5843430/65583056-d68dc780-df7e-11e9-831f-e1515f79d1e3.png">

When you try to search Hoogle for the current snapshot (lts-14.7), it fails with error `The given Hoogle database is not available. `(example link: https://www.stackage.org/lts-14.7/hoogle?q=aeson) It works fine for previous snapshot lts-14.6 (https://www.stackage.org/lts-14.6/hoogle?q=aeson)

**Comment by snoyberg** [comment]
Thanks, I'm investigating. The cron job was failing to upload to S3, I'm not sure why.

**Comment by snoyberg** [comment]
Best guess: we're suffering from the same bug as https://github.com/brendanhay/amazonka/issues/546. I just pushed a commit (2701f186cafe882cdc821e4c678526d106be772a) which quite hackily avoids chunked bodies. Let's see if that fixes it, should take 1-2 hours to go through all the build/cron job stuff.

**Comment by snoyberg** [comment]
Whew, that seems to have worked. Thanks for the report!
