### ISSUE TITLE
LTS 12.26 lost its Hoogle

### ISSUE THREAD

**Issue by ndmitchell** [fpco/stackage-server#284]
I see that LTS 12.26 lost its Hoogle search. https://www.stackage.org/lts-12.26/hoogle?q=filter gives:

> The given Hoogle database is not available.

Is there any chance of resurrecting Hoogle for that version? It's the last GHC 8.4 release, so there are a few companies that still use it.

**Comment by snoyberg** [comment]
We just updated Hoogle versions and are regenerating older databases, it takes a while. We typically regenerate 50 LTS snapshots.

**Comment by ndmitchell** [comment]
Sweet! Thanks a lot!
