### ISSUE TITLE
https://www.stackage.org/nightly times out

### ISSUE THREAD

**Issue by ndmitchell** [fpco/stackage-server#291]
The URL https://www.stackage.org/nightly takes forever (~30s), then displays 502 Bad Gateway. Been happening since 23 hours ago, since it takes out the Hoogle nightly update process.

**Comment by ndmitchell** [comment]
Seems to have recovered.

**Comment by snoyberg** [comment]
We're still investigating, this will likely continue off and on for a few
days.

**Comment by snoyberg** [comment]
This should now be fully resolved
