### ISSUE TITLE
"View changes" page times out

### ISSUE THREAD

**Issue by vaclavsvejcar** [fpco/stackage-server#294]
At least for me, any _View changes_ page (such as https://www.stackage.org/diff/lts-16.9/lts-16.10) just loads really long (>1min) and then times out. I noticed this few days ago, but the problem stil remains. Is this some bug, troubles with infrastructure or just not optimized piece of code responsible for getting the diff of changes?

**Comment by snoyberg** [comment]
There have been issues with the database queries recently. Most likely we need to add some indices to speed things up, but no one has had a chance to investigate thoroughly yet.

**Comment by snoyberg** [comment]
Actually, looks like this one was just a misconfiguration at the network level. This should now be working.
