### ISSUE TITLE
Search shows wrong snapshot version

### ISSUE THREAD

**Issue by dten** [fpco/stackage-server#305]
https://www.stackage.org/lts-16.12/hoogle?q=Aeson

shows search results for lts-17.0

clicking search again navs to 

https://www.stackage.org/lts-17.0/hoogle?q=Aeson

![image](https://user-images.githubusercontent.com/1019038/105874253-49380880-5ff4-11eb-8d12-44ecb6171d45.png)

**Comment by snoyberg** [comment]
I should clarify it better in the display. We were having disk space issues with providing access to all of the Hoogle snapshots, so we now only support a single LTS and a single Nightly. The alternative was causing unnecessary pod ejection.

**Comment by snoyberg** [comment]
I've added a comment at the top of each search result page, linking back to this issue.

**Comment by dten** [comment]
Ouch that's a shame but understandable

**Comment by simonmichael** [comment]
This caused a little confusion in #haskell today. If it's possible, I think having https://www.stackage.org/OLDVERSIONS redirect to https://www.stackage.org/ACTUALLYINDEXEDVERSION would make it much clearer.

**Comment by simonmichael** [comment]
Sorry, I meant the hoogle urls. Doing a hoogle search at https://www.stackage.org/lts-18.28 currently takes you to https://www.stackage.org/lts-18.28/hoogle?q=test, which is actually showing 19.23 results, hence the confusion.

**Comment by flip111** [comment]
> We were having disk space issues with providing access to all of the Hoogle snapshots

How much disk space is required? I might be interested to rebuild the docs locally since i have some old spare HDD's

Searching old versions was such a power feature, i'm not sure what to do without.
