### ISSUE TITLE
Search not returning results in `base`

### ISSUE THREAD

**Issue by dten** [fpco/stackage-server#314]
for example i would expect this to list Data.List 's head from base. It seems to recently have stopped doing this
https://www.stackage.org/lts-19.18/hoogle?q=head

**Comment by brandonchinn178** [comment]
It seems like any package bundled with GHC is affected. Searching "base" doesn't yield the package either, neither does "mtl", "transformers", etc.

**Comment by dten** [comment]
seems to not be a problem any more

**Comment by Shakadak** [comment]
It seems to be a problem again, even when searching from the input in the package page:
https://www.stackage.org/package/base
https://www.stackage.org/lts-21.15/hoogle?q=mapM&package=base
https://www.stackage.org/haddock/lts-21.15/base-4.17.2.0/Control-Monad.html#v:mapM
