### ISSUE TITLE
`stackage.org/diff/` shows some updates as delete+add

### ISSUE THREAD

**Issue by andreasabel** [fpco/stackage-server#315]
E.g. https://www.stackage.org/diff/nightly-2022-11-17/nightly-2023-03-31 shows `BNFC` and others as deleted and added rather than as updated.  
<img width="746" alt="Screenshot 2023-03-31 at 10 22 08" src="https://user-images.githubusercontent.com/1155218/229067333-b2ac8b7b-2ad9-49ba-83d9-f6d64820abb8.png">
How come, and is this intended?

Also, e.g. `BNFC-meta` and `Boolean` have no visible diff in this listing, should they be mentioned at all?

P.S.: Hope this is the right repo to report this issue against; got here from
- https://github.com/commercialhaskell/stackage-content/issues/132

**Comment by alaendle** [comment]
My suspicion is that the problem is that comparison after toCaseFold is not the same as before - so line 80 and line 85 didn't lead to the same result:
[https://github.com/fpco/stackage-server/blob/master/src/Stackage/Snapshot/Diff.hs#L80](https://github.com/fpco/stackage-server/blob/041255cc29f2458e781004bcfe2b04a7d5f76f75/src/Stackage/Snapshot/Diff.hs#L80)

**Comment by andreasabel** [comment]
Ah, I had the suspicion that it had to do something with packages that use capital letters.  Good catch!

I would rewrite this code entirely to use a map from the package name to its 3-alternative state which I would populate from the two snapshot collection---rather than fiddling with lists...
The state could be `InA Version | InB Version | InBoth Version Version`.

**Comment by juhp** [comment]
(Thanks for reporting this - I too noticed it this week:

- `List` in https://www.stackage.org/diff/nightly-2023-06-23/nightly-2023-06-24

 and today:

- `Yampa` in https://www.stackage.org/diff/nightly-2023-06-24/nightly-2023-06-25

I was meaning to take a look... Actually surprised noone mentioned it before.)

Indeed looks related with capitalization.

**Comment by juhp** [comment]
@andreasabel is probably write, but naively looks to me that just removing that toCaseFold should fix this.

**Comment by andreasabel** [comment]
Which comes to me as a surprise is that the original implementation _did_ use maps as I suggest here, but @snoyberg changed it in b80a7f9a527288d44d1d242a1f185cc1625b3c14 to the current (imo convoluted) implementation with reason "no hashmaps needed", possibly introducing the current bug on the way.
Not sure what the motivation was to go from a structured solution to one using lists and folds...

**Comment by juhp** [comment]
Well I need to think more, but each package only appears once per snapshot: so isn't that the reason?
But quite possible I haven't thought about this enough... :-)

**Comment by andreasabel** [comment]
> each package only appears once per snapshot: so isn't that the reason?

Yeah, isn't this the reason why a map from package to its version/change info would be the appropriate data structure?  
Lists, in contrast, allow both for several occurrences of a package and a custom ordering.  Both are not wanted here, so lists are not a tight fit, and allow for bugs like this one.

**Comment by juhp** [comment]
Thank you - looks fixed now, indeed yay

**Comment by juhp** [comment]
@andreasabel You might be right - I can't really see a clear difference, but I am also not a CS ;-(
If you want to open a separate ticket, we can consider it more there later?

**Comment by andreasabel** [comment]
Not sure, the acute problem is gone, so there is likely little motivation for a refactoring.  It does not seem there is a lot of activity on this project, so there might be no time to work on non-pressing issues...
