### ISSUE TITLE
Create and populate a deprecated table

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#42]
We'd likely use it to filter the list of packages. The Hackage API for this is:

https://hackage.haskell.org/packages/deprecated.json

We should populate it from the same Data.Hackage code that's populating the other tables now, so that the work is done on the Jenkins server and not the live web servers.

**Comment by DanBurton** [comment]
Implemented these suggestions in commit ed23d5e. Chris please review.

**Comment by chrisdone** [comment]
LGTM.
