### ISSUE TITLE
Add Hoogle capabilities to stackage.org

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#47]
Need to start embedding textual Hoogle database in doc bundles.

* [x] Modify the documentation unpacker to generate Hoogle binary databases. If the database in a given location can't be loaded, delete the old database and try generating a new one (to deal with upgraded Hoogle versions). https://github.com/fpco/stackage-server/blob/master/Handler/Haddock.hs#L213
* [x] Create a web UI for accessing this. Have a search bar on each snapshot page, and possibly one on the homepage.

**Comment by snoyberg** [comment]
When this is complete, I think we should also add a Hoogle search box on the homepage, which will search the most recent LTS release.

**Comment by ndmitchell** [comment]
Btw, if you have any stats on how many searches are done, what the CPU/Memory cost is, how many searches take > some threshold etc. I'd be very curious. I also notice you have "instant search" turned off, is that deliberate for performance reasons? Or just not something you knew could be turned on?

**Comment by snoyberg** [comment]
We have a completely separate web UI for Hoogle, so we can't take advantage of instant search automatically.

We're still working out some issues with the Hoogle database generation itself, so this isn't quite "prime time" yet. Once that's sorted, we can start collecting stats and making UI improvements.

**Comment by ndmitchell** [comment]
I'm working on simplifying and speeding up database generation, so I wouldn't invest too much effort before I do that.

**Comment by snoyberg** [comment]
It's issues on our end, regarding the ordering of unpacking of our (very large) documentation tarballs and how that impacts the blocking nature of things.

**Comment by snoyberg** [comment]
@ndmitchell OK, I implemented the improvements that I wanted to make, so now I can report back on the Hoogle front itself. I'm seeing two pain points:

1. Merging the databases is taking a *lot* of memory (1.5 GB or so). While on my dev machine that's no big deal, it's quite a burden on a live web server. So ideally we'd pre-compute the Hoogle binary databases instead of generating them live, except...
2. The binary database format is intrinsically tied to the version of Hoogle it was generated with, so that if we ever upgrade Hoogle on the server or on the database-generating machine, we'll have version mismatches.

So my ideal situation would be for some consistent binary format which is backwards compatible (not necessarily with existing databases, but with databases that come into existence from a certain date onwards). Then I'd generate the Hoogle binaries at the same time as I generate all of the Haddock docs, and the web server would just need to download it. The secondary request would be to reduce memory usage during, but frankly that's less important if this second point is implemented.

I'm sure I'll have comments about CPU or memory usage of the Hoogle searches themselves, but as it stands the memory stats on the server are totally swamped by the generation process.

**Comment by snoyberg** [comment]
By the way, if it would be more useful, I can move that comment into a new issue against the Hoogle issue tracker.

**Comment by ndmitchell** [comment]
The comments are just as useful here - the Hoogle bug tracker needs a cleanup anyway, so they might be easier to find here at the moment :)

* 1.5Gb is both less than I was expecting, and doesn't seem that huge a burden on a live web server - maybe my 32Gb web servers are corrupting me.
* I don't ever expect to have complete version independence. I'll probably go for 0.0.1 releases maintaining database format. Is keeping the versions in sync that difficult?

**Comment by snoyberg** [comment]
Keeping the version *in sync* isn't difficult. The difficulty is that we want to provide Hoogle capabilities for historic snapshots, of which there are many. I suppose we could have a job that, each time we bump the Hoogle versions, goes through all of our old snapshots and regenerates the Hoogle databases.

**Comment by ndmitchell** [comment]
I don't know how long it takes at the moment, but I'm targeting a time of ~5 mins to generate a database for all of Stackage.

**Comment by snoyberg** [comment]
I've just set it up so that Hoogle binary databases are persisted to S3 based on both the snapshot ID and the Hoogle library version. I'm generating my libraries on my dev machine and uploading them to S3 (we *should* automate that process and have it as part of our Jenkins jobs), and I've also disabled database creation/merging on the main server, which avoids the memory issue.

**Comment by snoyberg** [comment]
I think this issue is now resolved, as the resource problems have been fixed. Closing, thanks @mgsloan and @ndmitchell.
