### ISSUE TITLE
System-wide Stackage Install

### ISSUE THREAD

**Issue by creichert** [fpco/stackage-server#67]
While there is plenty of documentation for setting up stackage in a cabal project, I don't think it's completely clear how to setup a system-wide stackage install.

For example:

I have a fresh install of ghc and cabal, now I want to install yesod-bin and start a new project. However, I want to install yesod-bin from a stackage snapshot.

Currently, most of the instructions are for existing cabal projects or sandbox directories.

My suggestion was to change the remote-repo in the ~/.cabal/config to match the cabal.config distributed on the quick start guide. 

This guide suggest copying into cabal project:
http://www.stackage.org/

This Stackage FAQ does suggest changing the remote-repo but not in the ~/.cabal/config file:
https://github.com/fpco/stackage/wiki/Stackage-Server-FAQ

I could be confused myself on the system-wide instructions as I primarily sandbox projects. Could this use some clarification? (I can make these updates)

**Comment by garry-cairns** [comment]
Don't know if this is related but I'm having [terrible trouble](http://stackoverflow.com/questions/29155497/how-do-i-run-yesod-init-from-a-docker-container) trying to set up stackage and yesod inside a Docker container.

I've tried the Dockerfile linked to in that question and also a more basic one using the hvr ppa. In the latter case using the global cabal config results in cabal complaining about an `unrecognised field constraint` on every line and finishing with the cryptic (to me) `cabal: fromFlag NoFlag. Use fromFlagOrDefault`.

**Comment by creichert** [comment]
@garry-cairns I commented on: https://github.com/yesodweb/yesod/issues/960

The global cabal config (http://www.stackage.org/snapshot/nightly-2014-12-22/cabal.config?global=true) only works at `~/.cabal/config`.

There could be a discrepancy in the install instructions but try sticking as close to the install instructions as possible and pasting your output so we can help.

**Comment by psibi** [comment]
@snoyberg I feel the current quick-start section is confusing in stackage.org. Currently it states that:

"Download the following file, place it next to your cabal config file "

Now it's not clear which config file ? Is it system-wide ~/.cabal/config or the cabal file related to a package. In fact this [comment](https://github.com/fpco/stackage-server/issues/67#issuecomment-67742772) of yours explains them properly. I think that message should be clearly conveyed in the home page.

**Comment by snoyberg** [comment]
Good catch, do you think this clears it up? https://github.com/fpco/stackage-content/commit/a5e6b0426cae4c34f60d84f90dcad739448fbe1e

**Comment by psibi** [comment]
Thanks, that's perfect!
