### ISSUE TITLE
Support live hoogle search

### ISSUE THREAD

**Issue by chrisdone** [fpco/stackage-server#73]
This is to support as-you-type searching on the /hoogle page.

**Comment by chrisdone** [comment]
@mgsloan @snoyberg The current hoogle search is too slow to support live searching
in a reasonable way. Is there some missing configuration/setup to enable live searching or is Hoogle simply too slow on the complete Stackage package set? Example:

    chris@retina:~$ time curl 'http://www.stackage.org/snapshot/lts-1.11/hoogle?q=Monad'  -s -o /dev/null
    real	0m1.604s

**Comment by snoyberg** [comment]
I believe the issue is that we currently reopen the database from scratch
each time, due to some memory usage concerns. Is that correct Sloan?

**Comment by mgsloan** [comment]
Yup, that's correct.  I've forwarded @chrisdone the email conversation with neil regarding hoogle performance.

**Comment by chrisdone** [comment]
I take back this feature request in favor of `stack hoogle` and related tooling.
