### ISSUE TITLE
defaultLayout should include <div .container>

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#75]
Currently every template needs to include this, with a few exceptions. Instead, we should have an auxiliary function along the lines of `defaultLayoutWithoutContainer` for those cases.

**Comment by chrisdone** [comment]
Special pages are:

* The homepage.
* The package page.

**Comment by DanBurton** [comment]
@chrisdone PTAL

I've added a branch, default-layout-container. I've only changed the defaultLayout template so far. (see commit 1d7de2b.) This change appears to have no visual effect on any of the pages (am I wrong?), so I presume it's okay to merge this into master as it is. Then we can incrementally simplify existing templates as desired.

**Comment by chrisdone** [comment]
Lovely jubbly. Merging.

**Comment by DanBurton** [comment]
Cool. Deleted the branch.
