### ISSUE TITLE
Remove the "view" code

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#79]
At the beginning of stackage-server development, I added a feature to have different "views" of Hackage, such as the strict-PVP view. It was an interesting experiment, but I don't think it helps anyone. At this point, it just takes up space in the database, and makes the cabal-loader process take a lot longer to run. This issue is to propose removing the code.

**Comment by snoyberg** [comment]
Email sent to mailing list (https://groups.google.com/d/msg/stackage/djjFKsFQEo8/N62oCH5NkcIJ). Will wait a week for responses before moving ahead with this.

**Comment by creichert** [comment]
Is the Hackage mirror currently down? http://hackage.fpcomplete.com/

**Comment by snoyberg** [comment]
Please see this message: https://groups.google.com/d/msg/stackage/djjFKsFQEo8/gc2oGmCM380J

**Comment by snoyberg** [comment]
No one complained, so let's move ahead with killing this code.
