### ISSUE TITLE
Don't make snapshot active until hoogle database and docs are ready

### ISSUE THREAD

**Issue by borsboom** [fpco/stackage-server#81]
Currently, when a new snapshot is uploaded it becomes immediately active before its hoogle database and documentation are ready.  This means that, for example, <https://www.stackage.org/lts/hoogle> fails with the message "The given Hoogle database is not available" for several hours every week.

**Comment by snoyberg** [comment]
Given the much shorter window now (~30 minutes), you OK with leaving this as is and closing?
