### ISSUE TITLE
Document the process of uploading snapshots to your own stackage-server instance

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-server#85]
Here are my notes on the process, some of which was copied from @snoyberg's email last week.

```
$ stacakge-sever Development # or whatever
```

* log into your stackage-server with persona # or whatever
* navigate to /profile
* take note of your username, copy your auth token to clipboard

* edit your config/settings.yaml. Make sure your username is listed as an admin user. e.g.:
  ```
  admin-users:
    - danburton
  ```
* Restart stackage-server as necessary.

```
$ cabal install stackage-curator
```

* Create a file /auth-token that has the token from your profile page (/profile) on the local Stackage Server
* OR, set the STACKAGE_AUTH_TOKEN env variable

```
$ stackage-curator upload2 downloaded-file.bundle --server-url http://your-stackage-server
```

----

Misc thoughts:

[error] uploaded with the name nightly-[todays-date].
Ideally should be downloaded-file.bundle name instead.

[inconvenience] "merging" the hoogle db is slowing down (preventing?) regular requests.

[inconvenience] hoogle db doesn't start generating until requested?

**Comment by snoyberg** [comment]
These steps should be added to the README.

What do you mean by your `[error]` note?

I don't believe your final comment about hoogle DB generation is correct.

**Comment by DanBurton** [comment]
> These steps should be added to the README.

Should we include a link to the sample bundle? Should stackage.org provide links to "download snapshot bundle"?

> What do you mean by your [error] note?

When I ran:

```
stackage-curator upload2 stackage-nightly-2015-03-26.bundle --server-url http://localhost:3000
```

It uploaded it as a snapshot named `nightly-2015-04-03` (not 03-26). I was expecting it to be named according to the bundle name, rather than according to the date of upload, and I wasn't expecting it to actually be added to the "nightly" table, since I used `upload2` instead of `upload-nightly` (and I presumed that the latter is for that purpose).

> I don't believe your final comment about hoogle DB generation is correct.

You're probably right. It seemed as I noted based on my ad-hoc testing, but that could have been purely coincidence.

**Comment by snoyberg** [comment]
The nightly name is determined by the server, not the client, and is based on upload date. This is the intended behavior, though it's a good idea to document this properly. Also, upload2 is called that because it's replacing the old upload-nightly, and in fact I believe the newest stackage-curator completely gets rid of upload-nightly and renames upload2 to upload.

**Comment by DanBurton** [comment]
Documented. @snoyberg please review [the README](https://github.com/fpco/stackage-server#readme).

**Comment by snoyberg** [comment]
Should the README have a link to a sample bundle tarball to use? I think I sent you a URL for that.

**Comment by DanBurton** [comment]
Added link to sample bundle. @snoyberg any other feedback?

**Comment by snoyberg** [comment]
Nope, looks good, thanks.
