### ISSUE TITLE
Minor problems with download page

### ISSUE THREAD

**Issue by snoyberg** [fpco/stackage-server#93]
I realize the page isn't ready for prime-time usage yet, but just wanted to mark down some observations:

* [x] No title is set on the page's widget, so the title tag ends up being `:: Stackage Server`
* [x] There are a number of empty ul tags in the page
* [x] I'd recommend having a link somewhere on the page to the Github repo for this project so people can get more information

**Comment by DanBurton** [comment]
It's still not ready for prime time, but I've addressed those minor points.
