### ISSUE TITLE
Address TODO regarding stackage binary

### ISSUE THREAD

**Issue by DanBurton** [fpco/stackage-server#98]
https://github.com/fpco/stackage-server/blob/master/Types.hs#L113

Originally, I intended to distribute the `stackage` binary as a special auto-updater that would get the rest of stackage-cli automatically.

What we might do instead is just decide to distribute `stackage-setup` as we are, and have the instructions be to use `stackage-setup`, which will in turn get the rest of stackage-cli using the same framework it uses to get `ghc`, `cabal`, etc. In that case, I'll just delete the TODO once this functionality has been built in.

**Comment by snoyberg** [comment]
No longer relevant
